trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/Data Analysis'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/piwebapi_samples/Data Analysis'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/piwebapi_samples/Data Analysis'
  - name: CredFile
    value: test_config.py
  - name: CredFileLibrary
    value: product-readiness.piwebapi_python.py
  - name: covStream
    value: PIWebAPIPython
  - name: bdProject
    value: PIWebAPI_Python

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Test
      demands: COMPUTERNAME -equals $(buildAgent)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - script: |
          echo Starting
          echo %DATE% %TIME%
          set
          dir *.*
          echo Ending
        workingDirectory: $(Build.SourcesDirectory)$(projPath)
        displayName: 'Run tests'

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**\output.xml'
          searchFolder: $(Build.SourcesDirectory)$(projPath)
          testRunTitle: 'Publish test results'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: python
