# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
- group: LocalServer
- name: projpath
  value: /piwebapi_samples/Angular/AngularPIWebAPISample
- name: CredFile
  value: appsettings.json
- name: CredFileLibrary
  value: prod_omf_appsettings.json
- name: CredFileLibraryOP
  value: prod_onprem_omf_appsettings.json
- name: testpath
  value: /piwebapi_samples/Angular/AngularPIWebAPISample
- name: job
  value: OMF_APIDotNet

trigger:
- dev

pool:
  name: 00-OSIManaged-Test
  demands: USERNAME -equals $(LocalServer)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install -g @angular/cli
  displayName: 'npm install angular'
  workingDirectory: $(Build.SourcesDirectory)$(projpath)

- script: |
    npm install
    npm install --only=dev
  displayName: 'npm install dev dependencies'
  workingDirectory: $(Build.SourcesDirectory)$(projpath)

- script: ng test --watch=false
  displayName: 'run tests'
  workingDirectory: $(Build.SourcesDirectory)$(projpath)

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TESTS-*.xml'
